### PR TITLE
fix: defaultMigrationAuthor not set from spring configuration

### PR DESCRIPTION
**Pull request by lnu**
## Issue reference

flamingock/mongock#100

[Reference or link to the issue covered in the PR]

## Documentation PR reference

[Reference or link to the Pull request on the documentation project, performing the required update reflecting your change]
[Documentation project](https://github.com/mongock/mongock-docs)

## Description and context

[The code should be self explanatory. However this should help us to understand what your code does, any specific pattern or design used, etc.]

## Benefits

[What benefits will be realized by the code change?]

## Possible Drawbacks

[What are the possible side-effects or negative impacts of the code change?]

## Checklist 
- [ ] Unit tests provided
- [ ] Integration tests provided 
- [ ] Documentation updated in [documentation project](https://github.com/mongock/mongock-docs)
- [ ] Updated example in [example projects](https://github.com/mongock/mongock-examples)

### CODE REVIEW

**Comment by lnu** [comment]
tests on their way

**Comment by dieppa** [comment]
Hello @lnu ,

It looks good to me. However, although I know there is no test covering this at the moment, if you could add some test, at least covering your change, it would be appreciated.

The class is mongock-core/mongock-api/src/test/java/io/mongock/api/config/MongockConfigurationTest.java

Thanks

**Comment by dieppa** [comment]
> Hello @lnu ,
> 
> It looks good to me. However, although I know there is no test covering this at the moment, if you could add some test, at least covering your change, it would be appreciated.
> 
> The class is mongock-core/mongock-api/src/test/java/io/mongock/api/config/MongockConfigurationTest.java
> 
> Thanks

I spoke too soon 😄

**Comment by lnu** [comment]
Be careful that if someone set the default-migration-author property before this change, all his changeunits will be reapplied since the author of the old commit is "default_author" and the new one will be the one set in the config file(author is taken into account to check if the changeunit is applied or not).  
correct?

**Comment by dieppa** [comment]
> Be careful that if someone set the default-migration-author property before this change, all his changeunits will be reapplied since the author of the old commit is "default_author" and the new one will be the one set in the config file(author is taken into account to check if the changeunit is applied or not). correct?

Thanks. I didn't spot that. It's an important bit. So let's us to think about it and try to come up with the best decision 😃

**Comment by dieppa** [comment]
hello @lnu , sorry for the delay. We have been discussed this issue and we have decided that it's better to keep the current setter like it's, marked as `deprecated`, removed in following versions, and another field with a different setter, let's call it `setBaseAuthor`(suggestion are welcome). 

It's not great, but it's the only way we see that we can fix this without potentially adding a breaking change.

**Comment by lnu** [comment]
@dieppa It's definitely a good idea to avoid a breaking change like that. `setDefaultAuthor` is maybe a better fit than `setBaseAuthor`?

**Comment by dieppa** [comment]
> @dieppa It's definitely a good idea to avoid a breaking change like that. `setDefaultAuthor` is maybe a better fit than `setBaseAuthor`?
 

Ah true!! I was assuming the setter was already called `setDefaultAuthor`. In that case, even better, we wanted to progressively deprecate the concept `migration`.

Great stuff!

**Comment by dieppa** [comment]
Hello @lnu , there is no rush, you are the only one that has notice this, but will you be performing this change?
Thanks

**Comment by lnu** [comment]
I can check it and update the pr

**Comment by dieppa** [comment]
Hi @lnu , this means you are not carrying on with this change?

**Comment by lnu** [comment]
=> https://github.com/mongock/mongock/pull/634

back from vacations, I'm testing it locally

**Pull request closed without merging**
