### PR TITLE
Upgrade to Spring 5.0.x and Spring Data 2.x

### PR DESCRIPTION
**Pull request by engan81**

### CODE REVIEW

**Comment by dieppa** [comment]
@engan81 thanks for your contribution. I will add it, but first I need to check some other stuff, maybe adding more tests and make sure everything is fine.

If you really needs this, let me know so I can do a workaround and release a BETA version for you

**Comment by engan81** [comment]
@dieppa sounds good! I fully understand that this needs to be thoroughly tested before it is released.
If it isn't too much work for you I would really appreciate a BETA version for this. I will then run it in a live project and of course fix/report any issues found with the update as well.

**Comment by dieppa** [comment]
@engan81 thanks. I will try to make a BETA release for you tonight based on your change

**Comment by dieppa** [comment]
@engan81 can I ask you to **star** the project? Thanks

*I mean mark it as star if you use it and like it, so it gets some reputation

**Comment by engan81** [comment]
Of course, star added now.

**Comment by dieppa** [comment]
Great! appreciated

**Comment by dieppa** [comment]
@engan81 I released a BETA version with your Spring -springboot2 changes.
2.0.0-BETA

**Comment by dieppa** [comment]
I publish this in the readme, the more people using the better

**Comment by dieppa** [comment]
@engan81 have you tested the BETA version.If so, how did it go?

**Comment by engan81** [comment]
I have upgraded in one project and see no problems there. I have not run any complete tests of Mongock, just used it (and so far all features we are using seems to work).

**Comment by dieppa** [comment]
Good thanks!

**Comment by dieppa** [comment]
@engan81  we have tested and works fine. Can you please update your branch with the latest changes in master, so we can approve this pull request? Thanks

**Review by dieppa — CHANGES_REQUESTED** [review]
please rebase from master

**Comment by sgrillon14** [comment]
@engan81 , can you rebase your branch please. Is it for the merge of this part.

great thanks a lot in advance.

**Comment by engan81** [comment]
I approved the pull request on my fork and have updated this branch, Travis check passed.
Is there anything else I need to do?

**Review by dieppa — APPROVED** [review]

**Pull request merged**
