### PR TITLE
Make setters package-private

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by dieppa** [comment]
@mbuccat  the changes are right, but we are missing some others. Please have a look to children classes. For example, methods like setJongo should be package-private too.

Thanks

**Review by dieppa — CHANGES_REQUESTED** [review]
The changes are right, but we are missing some others. Please have a look to children classes. For example, methods like setJongo should be package-private too.

**Comment by dieppa** [comment]
@mbuccat, now it's actually wrong. When I said there are some other methods that shouldn't be exposed, I meant in the Mongock class(and children), no the builders. The builders are actually the interface to create an instance of the class, so its methods need to be public.

I suggest to revert the last commit and just change the setters on JongoMongock, SpringMongo and SpringbootMongock.

**Comment by ghost** [comment]
@dieppa
I updated the setters in JongoMongock and SpringMongock. However, I didn't see any setters in the SpringBootMongock file.

**Comment by dieppa** [comment]
@mbuccat ,This is more likely. It's fine, in SpringBootMongock there is a setter(wrongly missing 'set') which is already package-private, so it's fine.

I will review it later and hopefully merge it.
Thanks

**Review by dieppa — APPROVED** [review]

**Pull request merged**
