### PR TITLE
Split into separate maven modules (solves #15)

### PR DESCRIPTION
**Pull request by mmindenhall**
This PR borrows heavily from [mongobee PR#64](https://github.com/mongobee/mongobee/pull/64).

Basically, it splits mongock into three separate maven modules (mongock-core, mongock-jongo, mongock-spring).  The tests have also been split and refactored in each module.

There are probably some additional refactorings that can be done in the future (e.g., reduce code duplication), but I think this is a good start for being able to use mongock with and without Spring or Jongo.

I just realized I forgot to update the README, so I'll do that and push in a separate commit.  Please wait for that before merging.

### CODE REVIEW

**Comment by dieppa** [comment]
I was also doing the split, looks pretty much the same. I will carry on from yours as it's finished.
I will review it tomorrow.

Thanks

**Comment by mmindenhall** [comment]
Sorry...I should have let you know I was going to give it a crack.

**Comment by dieppa** [comment]
No worries, next time ;)

**Review by dieppa — APPROVED** [review]
Still some refactor needed, but nice work there. Thanks!

**Pull request merged**
