### PR TITLE
fix: new defaultAuthor(replace defaultMigrationAuthor)

### PR DESCRIPTION
**Pull request by lnu**
## Issue reference

see https://github.com/mongock/mongock/pull/632

wip

## Checklist 
- [ ] Unit tests provided
- [ ] Integration tests provided 
- [ ] Documentation updated in [documentation project](https://github.com/mongock/mongock-docs)
- [ ] Updated example in [example projects](https://github.com/mongock/mongock-examples)

### CODE REVIEW

**Comment by dieppa** [comment]
LGTM

**Comment by dieppa** [comment]
Hello, thanks for the changes!. This is in draft. What do you think is missing to have it ready?

**Comment by lnu** [comment]
> Hello, thanks for the changes!. This is in draft. What do you think is missing to have it ready?

Hi, sorry for the delay, I’m on vacation now. It’s still in draft because I did not test it, except the unit tests. If you think it’s ok, I can move it from draft.

**Comment by dieppa** [comment]
No, there is no rush on this. You are the only one noting is, so we prefer merge it when you are confident.

Enjoy your holidays 😃

**Comment by lnu** [comment]
tested locally and works as expected:

- if not set, default_author is set as before
- if set, the value of the property is used and applied to all changelog

**Comment by dieppa** [comment]
Thanks a lot. As you say, it seems it works as expected. But I will review it as soon as possible and if everything is ok, I merge it.

Thanks again!

**Review by dieppa — APPROVED** [review]
LGTM.
We'll release it in the following days. 
Thanks @lnu !

**Pull request merged**
